version: '3'

volumes:
  pg_data6:
  static:
  media:

services:
  db6:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data6:/var/lib/postgresql/data

  backend:
    image: damened/foodgram_backend
    env_file: .env
    depends_on:
      - db6
    volumes:
      - static:/backend_static/
      - media:/app/foodgram/media/

  frontend:
    image: damened/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    image: nginx:1.19.3
    ports:
      - "8800:80"
    volumes:
      - /home/yc-user/foodgram/nginx.conf:/etc/nginx/conf.d/default.confs
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/redoc.html:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend