version: '3'

volumes:
  pg_data6:
  static:
  media:

services:
  db6:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data6:/var/lib/postgresql/data

  backend:
    image: damened/foodgram_backend
    build: ../backend
    restart: always
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    env_file:
      - ../.env

  frontend:
    image: damened/foodgram_frontend
    build: ../frontend
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: damened/foodgram_nginx
    restart: always
    ports:
      - 8800:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend