version: '3'

volumes:
  pg_data6:
  static:
  media:

services:
  db6:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data6:/var/lib/postgresql/data

  backend:
    image: damened/foodgram_backend
    env_file: .env
    depends_on:
      - db6
    volumes:
      - static:/backend_static
      - media:/app/media/

  frontend:
    image: damened/foodgram_frontend
    env_file: .env
    depends_on:
      - backend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  nginx:
    image: damened/foodgram_nginx
    env_file: .env
    ports:
      - "8800:80"
    volumes:
      - static:/staticfiles/
      - media:/static/media/
    depends_on:
      - backend