version: '3'

volumes:
  pg_data6:
  static:
  media:

services:
  db6:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data6:/var/lib/postgresql/data

  backend:
    image: damened/foodgram_backend
    depends_on:
      - db6
    volumes:
      - ../static/:/app/static/
      - ../media/:/app/media/recipes/
    env_file:
      - ./.env
    restart: always

  frontend:
    image: damened/foodgram_frontend
    env_file: .env
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: damened/foodgram_nginx
    env_file: .env
    ports:
      - "8800:80"
    volumes:
      - ../static/:/var/html/static/
      - ../media/:/var/html/media/recipes/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always