version: '3'

volumes:
  pg_data6:
  static:
  media:

services:
  db6:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data6:/var/lib/postgresql/data

  backend:
    image: damened/foodgram_backend
    env_file: .env
    depends_on:
      - db6
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    image: damened/foodgram_frontend
    command: 
    volumes:
      - static:/frontend_static/
    env_file: .env
  nginx:
    image: damened/foodgram_nginx
    ports:
      - 8000:80
    volumes:
      - static:/static/
      - media:/media/