version: '3'

volumes:
  pg_data6:
  static:
  media:

services:
  db6:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data6:/var/lib/postgresql/data

  backend:
    image: damened/foodgram_backend
    env_file: .env
    depends_on:
      - db6
    volumes:
      - static:/code/static_backend/
      - media:/code/media/

  frontend:
    image: damened/foodgram_frontend
    env_file: .env
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: damened/foodgram_nginx
    env_file: .env
    ports:
      - "8800:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - /docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static_backend/
      - media:/var/html/media/
    restart: always
    depends_on:
      - frontend