version: '3'

volumes:
  pg_data6:
  static:
  media:

services:
  db6:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data6:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db6
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
  gateway:
    build: ./nginx/
    image: nginx:1.19.3
    ports:
      - "8800:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend